# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resource\xml\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(737, 563)
        main_window.setMinimumSize(QtCore.QSize(544, 430))
        self.verticalLayout = QtWidgets.QVBoxLayout(main_window)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QWidget(main_window)
        self.title_bar.setStyleSheet("")
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout_3.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title = QtWidgets.QLabel(self.title_bar)
        self.title.setObjectName("title")
        self.horizontalLayout_3.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_minimize = QtWidgets.QToolButton(self.title_bar)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/img/dark/minimize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_resize = QtWidgets.QToolButton(self.title_bar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/img/dark/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_resize.setIcon(icon1)
        self.btn_resize.setObjectName("btn_resize")
        self.horizontalLayout_3.addWidget(self.btn_resize)
        self.btn_exit = QtWidgets.QToolButton(self.title_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exit.sizePolicy().hasHeightForWidth())
        self.btn_exit.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/img/dark/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_exit.setIcon(icon2)
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout_3.addWidget(self.btn_exit)
        self.verticalLayout.addWidget(self.title_bar)
        self.menu_bar = QtWidgets.QWidget(main_window)
        self.menu_bar.setObjectName("menu_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menu_bar)
        self.horizontalLayout_2.setProperty("layoutSpacing", 2)
        self.horizontalLayout_2.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_setting = QtWidgets.QToolButton(self.menu_bar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/img/dark/setting.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_setting.setIcon(icon3)
        self.btn_setting.setIconSize(QtCore.QSize(24, 24))
        self.btn_setting.setObjectName("btn_setting")
        self.horizontalLayout_2.addWidget(self.btn_setting)
        self.line = QtWidgets.QFrame(self.menu_bar)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.btn_open = QtWidgets.QToolButton(self.menu_bar)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/img/dark/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_open.setIcon(icon4)
        self.btn_open.setIconSize(QtCore.QSize(24, 24))
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_2.addWidget(self.btn_open)
        self.btn_save = QtWidgets.QToolButton(self.menu_bar)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/img/dark/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_save.setIcon(icon5)
        self.btn_save.setIconSize(QtCore.QSize(24, 24))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_saveas = QtWidgets.QToolButton(self.menu_bar)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/img/dark/save_alt.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_saveas.setIcon(icon6)
        self.btn_saveas.setIconSize(QtCore.QSize(24, 24))
        self.btn_saveas.setObjectName("btn_saveas")
        self.horizontalLayout_2.addWidget(self.btn_saveas)
        self.line_2 = QtWidgets.QFrame(self.menu_bar)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.btn_undo = QtWidgets.QToolButton(self.menu_bar)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/img/dark/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_undo.setIcon(icon7)
        self.btn_undo.setIconSize(QtCore.QSize(24, 24))
        self.btn_undo.setObjectName("btn_undo")
        self.horizontalLayout_2.addWidget(self.btn_undo)
        self.btn_redo = QtWidgets.QToolButton(self.menu_bar)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/img/dark/redo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_redo.setIcon(icon8)
        self.btn_redo.setIconSize(QtCore.QSize(24, 24))
        self.btn_redo.setObjectName("btn_redo")
        self.horizontalLayout_2.addWidget(self.btn_redo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_info = QtWidgets.QToolButton(self.menu_bar)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/img/dark/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_info.setIcon(icon9)
        self.btn_info.setIconSize(QtCore.QSize(24, 24))
        self.btn_info.setObjectName("btn_info")
        self.horizontalLayout_2.addWidget(self.btn_info)
        self.verticalLayout.addWidget(self.menu_bar)
        self.workspace = QtWidgets.QMainWindow(main_window)
        self.workspace.setObjectName("workspace")
        self.verticalLayout.addWidget(self.workspace)

        self.retranslateUi(main_window)
        self.btn_minimize.clicked.connect(main_window.showMinimized)
        self.btn_exit.clicked.connect(main_window.close)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Frame"))
        self.title.setText(_translate("main_window", "DIGITAL IMAGE PROCESSING"))
        self.btn_minimize.setText(_translate("main_window", "Minimize"))
        self.btn_resize.setText(_translate("main_window", "Resize"))
        self.btn_exit.setText(_translate("main_window", "Exit"))
        self.btn_setting.setText(_translate("main_window", "Setting"))
        self.btn_open.setText(_translate("main_window", "Open"))
        self.btn_save.setText(_translate("main_window", "Save"))
        self.btn_saveas.setText(_translate("main_window", "Save as"))
        self.btn_undo.setText(_translate("main_window", "Undo"))
        self.btn_redo.setText(_translate("main_window", "Redo"))
        self.btn_info.setText(_translate("main_window", "Infomation"))
import darkmode
